Canbus send ability
farm-ng/amiga-brain-api pull request #14
Opened 2022-10-26 22:29 UTC by Hackerman342

2022-10-26 22:54 UTC, ethanrublee commented on protos/farm_ng/canbus/canbus.proto
> +  rpc sendCanbusMessage(SendCanbusMessageRequest)
This should be a stream, to reduce the overhead of requests.

2022-10-27 00:08 UTC, Hackerman342 reviewed
Confirmed to work on an Amiga

2022-10-27 00:10 UTC, Hackerman342 commented on protos/farm_ng/canbus/canbus.proto
> +  rpc sendCanbusMessage(SendCanbusMessageRequest)
OK I will try that now. Since we haven't set stream as the request side yet, I wanted to make sure it works in the simplest case

2022-10-27 00:10 UTC, ethanrublee requested changes
Can you change the sendCanbusMessage interface to use the streaming API?

2022-10-27 00:12 UTC, ethanrublee commented on py/farm_ng/canbus/canbus_client.py
> +        state: CanbusServiceState = await self.get_state()
get_state() for every message will add a lot of latency, especially if trying to hit 50 hz communication cycle time.  if its done once per stream it should be ok.

2022-10-27 15:56 UTC, ethanrublee approved these changes

2022-10-27 16:47 UTC, merged